# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Sudoless performance monitoring for Apple Silicon processors
brew "macmon"
# Ruby version manager
brew "rbenv"
vscode "abusaidm.html-snippets"
vscode "alefragnani.bookmarks"
vscode "bung87.rails"
vscode "bung87.vscode-gemfile"
vscode "coenraads.bracket-pair-colorizer-2"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "groksrc.ruby"
vscode "hbenl.vscode-test-explorer"
vscode "juangerardomedellinibarra.sqlite-viewer-browser"
vscode "kaiwood.endwise"
vscode "mhutchie.git-graph"
vscode "mosapride.zenkaku"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-audio"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "oderwat.indent-rainbow"
vscode "pkief.material-icon-theme"
vscode "qwtel.sqlite-viewer"
vscode "rebornix.ruby"
vscode "sianglim.slim"
vscode "streetsidesoftware.code-spell-checker"
vscode "thekalinga.bootstrap4-vscode"
vscode "vscodevim.vim"
vscode "wingrunr21.vscode-ruby"
npm "@google/gemini-cli"
npm "alfred-emoji"
npm "corepack"
npm "yarn"
